print ("03")
w = input("Masukan daftar belanja 1:")
x = input("Masukan daftar belanja 2:")
y = input("Tambahkan data ke daftar belanja 1: ")
z = input("Tambahkan data ke daftar belanja 2: ")
print (" Daftar belanja 1 adalah:" , w +',' , end="")
print (y)
print ("Daftar belanja 2 adalah:" , x +',', end="")
print (z)       
